# === FONT
font_family JetBrainsMono Nerd Font
font_size 18.7

# === WINDOW
initial_window_width  82c
initial_window_height 24c
window_padding_width 30

# === WINDOW DECORATIONS
hide_window_decorations no

# === CURSOR
cursor_shape block
cursor_blink_interval 0

# === TERMINAL
term xterm-kitty

# === PERFORMANCE
repaint_delay 10
input_delay 3
sync_to_monitor yes

# === DISABLE BELL
enable_audio_bell no

# === SCROLLBACK
scrollback_lines 10000

# === MOUSE
copy_on_select yes
strip_trailing_spaces smart

# === URL
url_color #4A4A4A
url_style single

# === DISABLE CONFIRM WINDOW CLOSE
confirm_os_window_close 0

# === COLORS
# - BASIC
foreground              #56C96E
background              #0b0b0b
selection_foreground    #3E3545
selection_background    #56C96E
# - CURSOR
cursor                  #5497AB
cursor_text_color       #3E3545
# - URL
url_color               #5497AB
# - WINDOW
active_border_color     #56C96E
inactive_border_color   #219062
bell_border_color       #5497AB
# - TAB
active_tab_foreground   #3E3545
active_tab_background   #56C96E
inactive_tab_foreground #56C96E
inactive_tab_background #3E3545
tab_bar_background      #3E3545
# - MARKS
mark1_foreground #3E3545
mark1_background #5497AB
mark2_foreground #3E3545
mark2_background #56C96E
mark3_foreground #3E3545
mark3_background #299B51
# - COLORS
color #3E3545
color1 #5497AB
color2 #299B51
color3 #5497AB
color4 #219062
color5 #5497AB
color6 #219062
color7 #56C96E
color8 #62536F
color9 #6BADC1
color10 #56C96E
color11 #6BADC1
color12 #2AAA77
color13 #6BADC1
color14 #56C96E
color15 #70D988