$background      = #060604
$background-alt  = #0A0A06
$inactive        = #12120A
$accent1         = #1A1A10
$accent2         = #3D3320
$foreground      = #FFFFFF

$outline         = rgba(255,255,255)
$outline_variant = rgba(155,155,155)