# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#3E3545"

# Main text color
theme[main_fg]="#56C96E"

# Title color for boxes
theme[title]="#5497AB"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#56C96E"

# Background color of selected items
theme[selected_bg]="#219062"

# Foreground color of selected items
theme[selected_fg]="#3E3545"

# Color of inactive/disabled text
theme[inactive_fg]="#62536F"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#56C96E"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#5497AB"

# CPU box outline color
theme[cpu_box]="#299B51"

# Memory/disks box outline color
theme[mem_box]="#219062"

# Net up/down box outline color
theme[net_box]="#5497AB"

# Processes box outline color
theme[proc_box]="#56C96E"

# Box divider line and small boxes line color
theme[div_line]="#62536F"

# Temperature graph colors
theme[temp_start]="#299B51"
theme[temp_mid]="#5497AB"
theme[temp_end]="#56C96E"

# CPU graph colors
theme[cpu_start]="#299B51"
theme[cpu_mid]="#219062"
theme[cpu_end]="#56C96E"

# Mem/Disk free meter
theme[free_start]="#299B51"
theme[free_mid]="#219062"
theme[free_end]="#56C96E"

# Mem/Disk cached meter
theme[cached_start]="#5497AB"
theme[cached_mid]="#219062"
theme[cached_end]="#56C96E"

# Mem/Disk available meter
theme[available_start]="#299B51"
theme[available_mid]="#5497AB"
theme[available_end]="#56C96E"

# Mem/Disk used meter
theme[used_start]="#219062"
theme[used_mid]="#299B51"
theme[used_end]="#56C96E"

# Download graph colors
theme[download_start]="#5497AB"
theme[download_mid]="#219062"
theme[download_end]="#56C96E"

# Upload graph colors
theme[upload_start]="#299B51"
theme[upload_mid]="#5497AB"
theme[upload_end]="#56C96E"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#299B51"
theme[process_mid]="#5497AB"
theme[process_end]="#56C96E"
