general {
    # Gaps
    gaps_in = 5
    gaps_out = 15

    # Border
    border_size = 0

    # Other
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    # Rounding
    rounding = 5

    # Transparency (Focused/Unfocused) Window
    active_opacity = 1.0
    inactive_opacity = 0.8

    # Shadow
    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # Blur
    blur {
        enabled = true
        size = 5
        passes = 3
        ignore_opacity = true
        new_optimizations = true
        special = false
        popups = true
        xray = true
        vibrancy = 0.1696
    }
}